import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;

import '../models/package_spec.dart';
import 'process_service.dart';
import 'sdk_version_service.dart';

class PubspecService {
  final SdkVersionService sdk;
  final ProcessService process;

  PubspecService({required this.sdk, required this.process});

  /// LOAD SPEC (from pubspec.json or spec.json)
  Future<PackageSpec> loadSpec(String path) async {
    final cliRoot = File(Platform.script.toFilePath()).parent.parent.path;

    final file = File(p.join(cliRoot, 'seeds', path, 'pubspec.json'));

    if (!await file.exists()) {
      throw Exception('Spec file not found at ${file.path}');
    }

    final json = await file.readAsString();
    final data = jsonDecode(json) as Map<String, dynamic>;

    return PackageSpec.fromJson(data);
  }

  /// GENERATE pubspec.yaml MINIMAL (IMPORTANT)
  Future<void> generatePubspec({
    required String path,
    required String name,
    required List<String> dependencies,
    required List<String> dependenciesManual,
    required List<String> devDependencies,
    required List<String> devDependenciesManual,
  }) async {
    final buffer = StringBuffer();

    buffer.writeln('name: $name');
    buffer.writeln('description: Generated by FSDA CLI');
    buffer.writeln('version: 1.0.0');
    buffer.writeln('publish_to: none');
    buffer.writeln();

    buffer.writeln('environment:');
    buffer.writeln('  sdk: "${sdk.getCaretVersion()}"');
    buffer.writeln();

    if (dependenciesManual.isNotEmpty) {
      buffer.writeln('dependencies:');
      for (final dep in dependenciesManual) {
        buffer.writeln(dep);
      }
      buffer.writeln();
    }

    if (devDependenciesManual.isNotEmpty) {
      buffer.writeln('dev_dependencies:');
      for (final dep in devDependenciesManual) {
        buffer.writeln(dep);
      }
      buffer.writeln();
    }
  }

  /// INSTALL dependencies properly (YOUR REQUIREMENT)
  Future<void> installDependencies({
    required String path,
    required List<String> dependencies,
    required List<String> devDependencies,
  }) async {
    await process.run('dart', [
      'pub',
      'add',
      dependencies.join(' '),
    ], workingDirectory: path);

    await process.run('dart', [
      'pub',
      'add',
      '--dev',
      devDependencies.join(' '),
    ], workingDirectory: path);
  }
}
